# Generated by Django 2.2.9 on 2020-05-13 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.CharField(max_length=100)),
                ('customername', models.CharField(max_length=100)),
                ('customerlan', models.DecimalField(decimal_places=6, max_digits=9)),
                ('customerlon', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='bookmark',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('sourcename', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('customers', models.ManyToManyField(to='customer.Customer')),
            ],
        ),
    ]
