# Generated by Django 2.2.9 on 2020-05-13 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='customers',
        ),
        migrations.AddField(
            model_name='customer',
            name='bookmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Bookmark'),
        ),
    ]
