# Generated by Django 2.2.9 on 2020-05-13 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200513_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='bid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bookmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Bookmark'),
        ),
    ]
