# Generated by Django 2.2.9 on 2020-05-14 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200514_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='creationdate',
            field=models.DateField(default='2020-05-14'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bookmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Bookmark'),
        ),
    ]
